# Generated by Django 6.0.6 on 2026-06-22 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_rename_order_product_orderitem_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Catalog.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bouquets', 'Bouquets'), ('gifts', 'Gifts'), ('matching sets', 'Matching Sets')], default='bouquets', max_length=50),
        ),
    ]
